### PR TITLE
Fix i18n: Rename MESRI into MESR

### PR DESCRIPTION
**Pull request by annelhote**

### CODE REVIEW

**Comment by bzg** [comment]
If the fix is not enough or if I didn't understand the problem correctly, please let me know!

**Comment by garronej** [comment]
Hello @annelhote,  

How are you doing?  

Thank you for the PR!  

@bzg, I see that you just merged this. Tell me when you plan to deploy this fix to production (by bumping the package.json, waiting for the version to be bublished, then runniong ./sill-update.sh).  
Because we must also rename all MESRI -> MESR in sill-data/user.json  

Don't worry nothing will be broken in the meantime.

**Comment by garronej** [comment]
Ok I see you just did, I'm on it

**Comment by garronej** [comment]
@bzg It's done on the db.  

Note that until the version that includes this patch is in prod the MESR has no label:  

image

**Comment by bzg** [comment]
There is no `sill-data/user.json` in https://github.com/codegouvfr/sill-data.

**Comment by bzg** [comment]
Great, thank you!  I'll let @hjonin plan a deployment, hopefully tomorrow.

**Pull request closed without merging**
